runtime: python39  # Choose a supported runtime that matches your app's needs

entrypoint: gunicorn -b :$PORT main:app  # Adjust if your app is not in 'main.py' or not using 'app' as the Flask instance

env: standard
instance_class: F1  # You can choose different classes based on your needs

automatic_scaling:
  min_instances: 1  # Adjust based on your expected traffic
  max_instances: 3